object Token {

  val value = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjAwIiwib2JyYXNTb2NpYWxlcyI6WyJjb2JlcnRlYyIsIm1lZGljdXMiLCJvc2RlIl0sInBlcm1pc29zIjpbImFkbWluaXN0cmFjaW9uVmVudGEiLCJhdWRpdG9yaWEiLCJlc3RhZGlzdGljYSIsImxvZ2lzdGljYSIsInJlY3VwZXJhclZlbnRhIiwidXN1YXJpbyIsInZhbGlkYWNpb24iLCJ2ZW50YSJdLCJwZXJmaWxlcyI6WyJhZG1pbiJdfQ.nfM8D0xD09WKHqXnQ8PGdTknOqMpILAAMy6WZzDqeAc"
  val header = "Bearer " + value
}
