object Token {

  val value = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiMjAwIiwib2JyYXNTb2NpYWxlcyI6WyJjb2JlcnRlYyIsIm1lZGljdXMiLCJvc2RlIl0sInBlcm1pc29zIjpbImFkbWluaXN0cmFjaW9uVmVudGEiLCJhdWRpdG9yaWEiLCJlc3RhZGlzdGljYSIsImxvZ2lzdGljYSIsImxvZ2lzdGljYU9wZXIiLCJyZWN1cGVyYXJWZW50YSIsInVzdWFyaW8iLCJ2YWxpZGFjaW9uIiwidmVudGEiXSwicGVyZmlsZXMiOlsiYWRtaW4iXX0.OqbRymVRC2j0KMK0wR8sKOdBC0VNNxZ4wDFqx4K1z1U"
  val header = "Bearer " + value

  val operValue = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoiNDAwIiwib2JyYXNTb2NpYWxlcyI6WyJjb2JlcnRlYyIsIm1lZGljdXMiLCJvc2RlIl0sInBlcm1pc29zIjpbImF1ZGl0b3JpYSIsImxvZ2lzdGljYU9wZXIiLCJ2ZW50YSJdLCJwZXJmaWxlcyI6WyJvcGVyYWRvciJdfQ.QkyHbQDxWRItn6AxoKmv--3AEUjS6pflP8v4t9o9GM4"
  val operToken = "Bearer " + operValue
}
