package models

trait Perfiles {

  val OPERADOR_VENTA = "OPERADOR VENTA"
  val OPERADOR_AUDITORIA = "OPERADOR AUDITORIA"
  val OPERADOR_LOGISTICA = "OPERADOR LOGISTICA"
  val OPERADOR_VALIDACION = "OPERADOR VALIDACION"
  val SUPERVISOR_CALL = "SUPERVISOR CALL"
  val SUPERVISOR_VENDEDORAS = "SUPERVISOR VENDEDORAS"
  val ADMINISTRADO_VENTAS = "ADMINISTRADOR VENTAS"
  val SUPERVISOR_LOGISTICA = "SUPERVISOR LOGISTICA"
  val ESTADISTICAS = "ESTADISTICAS"
  val VENDEDORA = "VENDEDORA"
  val CADETE = "CADETE"
  val EXTERNO = "EXTERNO"
  val PROMOTORA = "PROMOTORA"
}
